### ISSUE TITLE
No option to leave App settings.

### ISSUE THREAD

**Issue by DilkhushBaman** [erickok/transdroid-search#105]
![Screenshot_20201016-124601](https://user-images.githubusercontent.com/72965740/96224675-99dba680-0fad-11eb-9c14-e8c28f9ebc8a.jpg)
This appears when we first open the app and maybe i am missing on something but there is no option to go back to the original app and i am stuck on this settings window.
When i press back it automatically closes the app

**Comment by erickok** [comment]
There is only one screen in this app (the Search settings app). You can use your device's back button as in any other app. 

I think you are trying to go into Transdroid? Then just start Transdroid, the app, instead of this Search settings app.

**Comment by DilkhushBaman** [comment]
> There is only one screen in this app (the Search settings app). You can use your device's back button as in any other app.
> 
> I think you are trying to go into Transdroid? Then just start Transdroid, the app, instead of this Search settings app.

Oh thankyou i got it.

**Comment by DilkhushBaman** [comment]
Can you tell me how to setup a server please?

**Comment by erickok** [comment]
For help with Transdroid you may mail me at transdroid@2312.nl or use basic setup guides on the internet such as this (old) one http://www.transdroid.org/download/%c2%b5torrent/ but it depends on which client you are trying to connect to.
