### ISSUE TITLE
[Feature Request] Prowlarr Support

### ISSUE THREAD

**Issue by Generator** [erickok/transdroid-search#109]
## Description
Like Jackett, Prowlarr is a indexer manager/proxy with RSS Search [Prowlarr#182](https://github.com/Prowlarr/Prowlarr/issues/182#issuecomment-899920833)

RSS Search works with transdroid-search:
https://host.domain/{indexerID}/api?t=search&q={query}&apikey={apiKey}

however download doesn't  
https://host.domain/{indexerID}/download?apikey={apiKey}&link={someHash?}&file={torrentTitle} 
(the hash from ```link=``` isn't the torrent hash)

EDIT: Looks like @lightglitch already started working on this issue #108

**Comment by lightglitch** [comment]
In my version I can had the torrents without a problem, my issue was only with the seeders numbers that wasn't correct.
The url in the link tag that I get in the RSS is correct.

**Comment by erickok** [comment]
I'll check out that project and the pr tomorrow.

**Comment by erickok** [comment]
Okay this looks cool. I want to try it out myself, so I'm setting up the project now and will try to get some RSS feed out of it. Should be straightforward. Sounds like the RSS structure it exposes should be standardized so regardless of the Indexer it should produce downloadable links.

**Comment by erickok** [comment]
Can you try with Search Module 4.3?

**Comment by reyqn** [comment]
I'm sorry, I can't seem to make it work. Searching seems to work, but results are always empty.
 
Searching the query manually in a browser returns results however.

Here is my query string:
http://ip:port/api/v1/search?query=%s&apikey=key

Am I doing anything wrong?

**Comment by Generator** [comment]
@reyqn its ``api/ID/`` not ``api/v1/``
Ex: https://IP:PORT/1/api?t=search&q=%s&apikey=<your key>
ID is the indexer ID 
test it on a browser, replace ``q=%s`` with some word (ex ``q=ubuntu``) see if it works

**Comment by reyqn** [comment]
Thanks, it seems like this works. the result from my original query wasn't rss so transdroid could not parse it.

I thought I could use it from the documentation, but they mention
>An aggregate multi-indexer endpoint will not be added due to the significant drawbacks of said functionality

I guess I'll just add one custom rss search by indexer
