### ISSUE TITLE
Integration as system search provider missing

### ISSUE THREAD

**Issue by Atrejoe** [erickok/transdroid-search#11]
Previously, maybe in an older version of Android. The search provider could be included in a system wide search.

Now in both Android 4.3 and 4.4 this seems to be missing. (Both on my nexus tablet as HTC one phone).
![screenshot_2014-03-28-07-55-22](https://cloud.githubusercontent.com/assets/585091/2546954/12632330-b646-11e3-8d38-d51728380268.png)

Is this a new restriction by Android or just a dropped feature?

**Comment by erickok** [comment]
I am not going to implement it as it is no longer supported by the default Google search app (see http://stackoverflow.com/a/28642155/243165).
