### ISSUE TITLE
Results for IPtorrents always return 0 results

### ISSUE THREAD

**Issue by fallenpixel** [erickok/transdroid-search#19]
Every search I try and do using IPtorrents as the search provider returns no results. I'm a registered user on the site, I've verified my credentials are correct and it happens on multiple devices. I've also made sure results for my query show up on the site itself.

**Comment by erickok** [comment]
IPTorrents support is not going to be fixed. Their Cloudfare DDoS protection prevents any of my login mimic attempts. My request to them to add a search API was (quite rudely, I must add) rejected. They explicitly do NOT want any mobile app to support IPTorrents (search).

**Comment by chrisawad** [comment]
I tried to add a custom site for IPTorrents using:

> https://iptorrents.com/t.rss?u=$user_id;tp=$secret;download;$category_ids;q=%s

This should produce an rss feed with items like this:

```
<item>
<title>...</title>
<link>https://iptorrents.me/download.php/$torrent_id/$file.torrent?torrent_pass=$secret</link>
<pubDate>Sat, 19 Jun 2021 02:41:59 +0000</pubDate>
<description>496 MB; TV/x264</description>
</item>
```

When I follow the link in chrome everything works beautifully and chrome downloads the .torrent, but transdroid gives me:    "The search results does not link to a .torrent file"

I know they said they don't want support for this built in, but I'm wondering if there's a way to we can do this with the custom site feature.

Note: I can get the list of all the item names in transdroid, but when I try to download one I get the above error.

**Comment by chrisawad** [comment]
The above is with the Torrent Search plugin btw...

I'll also add that if I copy the link tag from the xml generated by the above rss feed after loading it in chrome, into transdroid's (the main app) download via link feature, it does work successfully.

I suspect something is buggy in the Torrent Search plugin feature.

**Comment by erickok** [comment]
Unfortunately I no longer have an account on IPT so it's kinda hard to test...

**Comment by chrisawad** [comment]
Check my pull request. I only changed one line that makes logical sense and allows IPT rss feed searching and downloading. The torrent size still shows 0 bytes but everything else works.

**Comment by chrisawad** [comment]
I did another pull request that adds IPTorrents as a private torrent site that fixes everything including the torrent size. If you need an account to test, let me know. I can invite you. Just need an email so they can send the invite link.
