### ISSUE TITLE
Return min sdk to 8

### ISSUE THREAD

**Issue by victorKH** [erickok/transdroid-search#21]
Return min sdk to 8 (because old version of torrent client automatically download new apk and can't setup it).

**Comment by erickok** [comment]
Are you using this with Transdroid or some other app? Because Transdroid is already min SDK 14 for a while now.

**Comment by victorKH** [comment]
I'm using ttorrent client on android-8 device and this version is last for android-8. Maybe good practice to make some config file or use different url for update to new incompatible version with announce new sdk for developers of torrent clients?

**Comment by victorKH** [comment]
P.s.: Or maybe good choice for this issue is Android Support Library package?

**Comment by erickok** [comment]
Your issue is correctly placed. I honestly didn't think anyone still used this with Android 2.x, especially since Transdroid doesn't support android 2.x already for a long time. 

Are you using this with rTorrent or some other app?

**Comment by victorKH** [comment]
I'm using this with tTorrent client.

**Comment by erickok** [comment]
Fixed by 4f05039602b373206a1da4f45dd5544ce53bcca9 (incorrectly tagged to issue 8).
