### ISSUE TITLE
Problem with scambio etico search plugin

### ISSUE THREAD

**Issue by Snake87r** [erickok/transdroid-search#22]
Hello,
ther's a little problem with the scambio etico search engine,
If i made a research in the program there are 20 result, but if i made the research in the site there are 158 result (note, every page of the site have 20 result, so i think there are some error in the change page function)
This is the link of the site, and if you see there are a parameters for the page:
http://forum.tntvillage.scambioetico.org/index.php?act=allreleases&filter=one%20piece&releaser=&st=0&cat=0

Note:
st=0 parameter is the start torrent of the list, so if you write st=20 the result is page 2, st=40 page 3 etc..
Note2:
If you surpass with the parameter st the number of the torrent the site doesn't show an error, but simply doesn't show any torrent.

**Comment by Snake87r** [comment]
Another thing, is possible to see and download all magnet link without the need to login with this link, but the search function in the url doesn't work:
http://www.tntvillage.scambioetico.org/?releaselist

**Comment by erickok** [comment]
There is no paging system in the search plugin. So only the first page with results are shown. I do not plan to change this, as it is not really compatible with the way the search module communicates with the end app (Transdroid, tTorrent, etc.). Sorry, we have to live with this limitation as long as the sites do not provide any official search API and we have to rely on html page scraping.

Scambio Etico is a private site, so I do not think we should try to work around their login system and hack this one page that is not protected. Moreover, that search only provides links to the details (forum post) pages and not directly to the .torrent files.
