### ISSUE TITLE
Bring back ThePirateBay

### ISSUE THREAD

**Issue by stavfx** [erickok/transdroid-search#24]
ThePirateBay has been removed in verion 3.0, but the site has been back up for a while now.
Can we have it back as a pre-defined search engine?

**Comment by erickok** [comment]
What URL should I check. Honestly I lost track with TPB, proxies, domains, Old Pirate Bay...

**Comment by stavfx** [comment]
http://thepiratebay.org/search/KEYWORD/0/7/0

**Comment by chewy74** [comment]
TPB url is actually 
http://thepiratebay.to

The one currently in the search model does not work

**Comment by erickok** [comment]
thepiratebay.to seems to me an imitator site. That'd be okay, but they have no custom search API I can use.

thepiratebay.org is not working.

**Comment by stavfx** [comment]
http://thepiratebay.org/search/KEYWORD/0/7/0 will return 301, but if you follow the redirect, it works.
btw, it will redirect to a different domain every time (.am / .mm / .vg), but they are all authentic TPB clones as far as i can tell

**Comment by erickok** [comment]
Fixed in 471adde0f7ce369dc47d175171075612408c6f55. I used some proxy, as still many countries block the original domain(s).

**Comment by stavfx** [comment]
Awesome! thanks!
