### ISSUE TITLE
Add RARBG support

### ISSUE THREAD

**Issue by DJarvis1** [erickok/transdroid-search#25]
Hi, can rarbg.to be added to the default list of search sites?
Thanks.

**Comment by erickok** [comment]
They offer a proper Rarbg torrentapi. Awsome! The doc is at https://torrentapi.org/apidocs_v2.txt and the project is managed at https://github.com/rarbg/torrentapi

**Comment by DJarvis1** [comment]
Cool does that mean its easily added into the search app ?

**Comment by erickok** [comment]
Yes, working on it as we speak.

**Comment by erickok** [comment]
Just a temporary issue rarbg/torrentapi#2

**Comment by DJarvis1** [comment]
Hi, I started using the newer version of transdroid search....like the
rarbg option.  Work OK until I try and search for stuff that would be in
the XXX category.

I get no search results at all....is there something not right?

Thanks.

**Comment by erickok** [comment]
Yes, the RARBG API seems to exclude the xxx category by default. If I use an explicit query for ```category=1;4``` it works as you would like. However, that would include all other results which is obviously not what we want. You might want to file a bug report at https://github.com/rarbg/torrentapi/issues/ and ask them to change the default behaviour.

**Comment by DJarvis1** [comment]
Hi...I've been using Usenet for couple of yes now with torrents as a back
for when they fail etc....

Never heard of seedbox until I put your app on new phone and see the option
in the setting for them....

Does your app only Support the Xirvik based seedboxes or are others
supported?...seedboxes.c.c for example...

In not sure if it'll work out better or worse than Usenet at the moment
just mulling it over....

Cheers.

**Comment by erickok** [comment]
That's a question for Transdroid, not this area search module issue. But you can always enter the connection details manually for any home or seedbox setup.
