### ISSUE TITLE
White theme with white fonts

### ISSUE THREAD

**Issue by fernandog** [erickok/transdroid-search#29]
@erickok 
Screenshot

![screenshot_2015-06-30-14-54-03-1](https://cloud.githubusercontent.com/assets/2620870/8437877/765eb852-1f38-11e5-8f2e-f7de18e3c09c.png)

**Comment by fernandog** [comment]
@erickok can you confirm please?

**Comment by erickok** [comment]
Sorry ot is already fixed but I need to release and I am on leave.

**Comment by erickok** [comment]
By the way, technically this should go in the Transdroid repo issues. This transdroid-search repo is for the search module only (site adapters).

**Comment by erickok** [comment]
Fixed in erickok/transdroid#224 and its commit.
