### ISSUE TITLE
Transdroid Torrent Search Notification keeps showing up

### ISSUE THREAD

**Issue by rdarioc** [erickok/transdroid-search#38]
Guys, 

The first time I installed transdroid-search plug in was through the Google downloaded app called Flud.

It worked fine but I now keep receiving a notification ever 10 minutes saying "Transdroid Torrent Search Torrent download comlpete"

I run a rooted Android 4.4.2

I have uninstalled Flud, I have uninstalled Transdroid Torrent Search, I have re-installed one or both either using Google App Store or F-Droid. 

Nada.

Notification keeps showing up every 10 minutes or at boot.

Any idea?

Thank you in advance for your support

Best
Rosario

**Comment by erickok** [comment]
Hi Rosario,

The message is "Transdroid Torrent Search Torrent download comlpete"?
(including the typo)? This is not coming from Transdroid or the Torrent
Search module. It must be one of those apps, Flud or F-Droid, you have used
to install Transdroid. I recommend installing Transdroid simply through my
website (or if you prefer Transdrone through the Play Store -- the full
versions Transdroid is NOT available in the Play Store). You will receive
update notifications when a new version is available.

Cheers,
Eric

**Comment by rdarioc** [comment]
Hi Eric,

Thank you for your prompt reply.

The typo was my mistake,  I apologize.

Attached you will find a screenshots with the mentioned notification.

Can you please confirm me your app doesn't write such notification for
sure?

Thank you in advance for your kind reply.

Best regards
Rosario

On Wednesday, 23 December 2015, Eric Kok <notifications@github.com> wrote:

> Hi Rosario,
>
> The message is "Transdroid Torrent Search Torrent download comlpete"?
> (including the typo)? This is not coming from Transdroid or the Torrent
> Search module. It must be one of those apps, Flud or F-Droid, you have used
> to install Transdroid. I recommend installing Transdroid simply through my
> website (or if you prefer Transdrone through the Play Store -- the full
> versions Transdroid is NOT available in the Play Store). You will receive
> update notifications when a new version is available.
>
> Cheers,
> Eric
>
> On 23 December 2015 at 08:43, rdarioc <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Guys,
> >
> > The first time I installed transdroid-search plug in was through the
> > Google downloaded app called Flud
> >
> > It worked fine but I now keep receiving a notification ever 10 minutes
> > saying "Transdroid Torrent Search Torrent download comlpete"
> >
> > I run a rooted Android 442
> >
> > I have uninstalled Flud, I have uninstalled Transdroid Torrent Search, I
> > have re-installed one or both either using Google App Store or F-Droid
> >
> > Nada
> >
> > Notification keeps showing up every 10 minutes or at boot
> >
> > Any idea?
> >
> > Thank you in advance for your support
> >
> > Best
> > Rosario
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/erickok/transdroid-search/issues/38>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erickok/transdroid-search/issues/38#issuecomment-166832665>
> .
>


-- 
R.D. Contarino <rdcontarino@gmail.com>
skype: rdarioc

**Comment by erickok** [comment]
Sorry, I don't see any screenshot. (If you are replying via email, GitHub does not add attachements. You can either email me or add them on GitHub directly.)

**Comment by rdarioc** [comment]
Just forwarded to you the e-mail with the attachment to your gmail account.

Best
Rosario

On 23 December 2015 at 11:27, Eric Kok <notifications@github.com> wrote:

> Sorry, I don't see any screenshot. (If you are replying via email, GitHub
> does not add attachements. You can either email me or add them on GitHub
> directly.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erickok/transdroid-search/issues/38#issuecomment-166856733>
> .
>



-- 
R.D. Contarino <rdcontarino@gmail.com>
skype: rdarioc

**Comment by erickok** [comment]
OK. This is certainly not a message generated by Transdroid. It looks simply like a completed download by your browser or some other app you use to download apps.
