### ISSUE TITLE
Feature request: Allow customisation of built-in searches

### ISSUE THREAD

**Issue by Nurgus** [erickok/transdroid-search#40]
Allow setting a custom domain or ip address for built in searches to allow custom proxys.
Allow setting extra variables to the http request. I like to search only verified torrents on kat (verified=1) for example.

**Comment by alanthehat** [comment]
The ability to copy an existing search to a new search would help here, especially for the use-case noted above where there is little change to implement the new search

**Comment by Relys** [comment]
This would be nice. I noticed that thepiratebay (proxy) seems to be down.

**Comment by erickok** [comment]
I decided against this. I have played the 'Make it an option' game before and regret it. I also should just fix providers if they fail and not rely on users to configure them.
