### ISSUE TITLE
KickAssTorrents not yielding any results

### ISSUE THREAD

**Issue by gotson** [erickok/transdroid-search#41]
Since a few weeks/months the search on KickAssTorrents always return "No results for your query"

**Comment by erickok** [comment]
It works fine here. kat.cr is probably blocked in your country?

**Comment by gotson** [comment]
It is not blocked, it works fine from all of my devices, either on my Wifi home connection or from my mobile provider.

**Comment by gotson** [comment]
After a reinstall of Transdroid and Transdroid Search, it's working again.
