### ISSUE TITLE
Back arrow does not do anything

### ISSUE THREAD

**Issue by gotson** [erickok/transdroid-search#42]
On the search screen, clicking on the back arrow on the top-left corner does not do anything, it should take the user back to the main screen.
One has to use the back button of Android to actually go back.

**Comment by erickok** [comment]
The left arrow (up button) should bring you to the main screen of the app. I just tested that and it works here. What Android version do you use?

**Comment by erickok** [comment]
There is no search function in the Torrent Search app. This library only provides results to other apps. Are you referring to Transdroid? (If so, please file a bug report in https://github.com/erickok/transdroid)

**Comment by gotson** [comment]
Thanks, referenced as https://github.com/erickok/transdroid/issues/289
