### ISSUE TITLE
Add support for KAT (relaunched site)

### ISSUE THREAD

**Issue by binhex** [erickok/transdroid-search#49]
Hi, ive noticed the removal of the old KAT site from the list of search providers, just wondered if its possible to include support for the new official KAT site now its up and running?.

https://katcr.co/new/

**Comment by erickok** [comment]
Maybe. Looks okay but no official search API any more (there used to be an RSS-based search that I used). So we'd have to resort to screen scraping (and check if there is no Cloudflare DDoS protection).

**Comment by erickok** [comment]
I can not find any trustworthy and true KAT replacement. The site linked above has very limited and old content.
