### ISSUE TITLE
Dialog disappears on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [erickok/transdroid-search#51]
When i perform these sequences of events, the dialog on screen disappears:

Sequence 1:
1. Click on:
a. Asia Torrents
b. BIT-HDTV
c. BTN
d. Danishbits
e. HD-Torrents
f. gdbits.org
g. HoundDawgs
h. Ncore
i. RevolutionTT
j. Scambio Etico
k. TorrentDay
l. TorrentLeech
2. Orientation Change

**Comment by erickok** [comment]
This si by design (it is the default spinner behaviour). You can just click the spinner again to open the menu again.

**Comment by reverse-unina** [comment]
As regards the spinners i may agree. What about the dialogs? I have found several apps in which it does not happen, so I think it is not a default behaviour
