### ISSUE TITLE
Fail First search using rarbg

### ISSUE THREAD

**Issue by mcardia** [erickok/transdroid-search#53]
Searching using history combobox fails the first time using rarbg engine. Then i do it again and works. Just with me?

Moto x pure edition
Transdroid 2.5.7
Transdroid torrent search 3.7

**Comment by erickok** [comment]
Sorry I can't reproduce this is my tests or when trying in Transdroid.

**Comment by erickok** [comment]
Actually, it might be due to the RARBG request limiting of 1 req/2 sec.
