### ISSUE TITLE
Allow custom piratebay url

### ISSUE THREAD

**Issue by bicklp** [erickok/transdroid-search#54]
Not an issue but a request.
Add an entry in settings to enter a different url for ThePirateBay

i can see its hardcoded in the tbp adapter
private static final String DOMAIN = "https://theproxypirate.pw";

Possible to have this read from the new setting instead

**Comment by lozbrown** [comment]
To be fair the proxies frequently come and go so this could actually be prudent

**Comment by erickok** [comment]
I decided against this. I have played the 'Make it an option' game before and regret it. I also should just fix providers if they fail and not rely on users to configure them.

I have fixed the TPB provider again.

**Comment by alexknuckles** [comment]
Broken again. Please play "make it an option" again, it's my favorite game.

**Comment by erickok** [comment]
But no. Sorry.
