### ISSUE TITLE
Search site updates 

### ISSUE THREAD

**Issue by chewy74** [erickok/transdroid-search#60]
FYI, extratorrent.cc has permanently closed its doors. 
https://torrentfreak.com/extratorrent-shuts-down-for-good-170517/

Also, the demonoid search isn't bringing up any search results. 

Running search v3.8

Thanks

**Comment by Forage** [comment]
A few interesting alternatives that would be nice to have as a replacement since the list is getting quite short now:
- https://idope.se/
- https://www.1337x.to/
- https://torrentz2.eu/

**Comment by Paronfesken** [comment]
I suggest https://katcr.co/ please.

**Comment by erickok** [comment]
Removed ExtraTorrent. 1337x does not seem to exist any more. torrentz2eu only serves external links. katcr.co I do not trust the slightest to exist for any time or offer anything that other sites do.

**Comment by chewy74** [comment]
@erickok some old staff and uploaders from extratorrent formed a new site

https://www.ettv.tv/

If I find any new sites that looks promising I will let you know

**Comment by Forage** [comment]
https://www.1337x.to/ works just fine, it's only sometimes that it is unreachable.
