### ISSUE TITLE
add jackett support

### ISSUE THREAD

**Issue by dadof3sods** [erickok/transdroid-search#63]
Hi, not sure if it would be possible but could Jackett be added to the search, that would allow private trackers to be added to jackett and transdroid search to in turn  utilise that.
thoughts?

**Comment by erickok** [comment]
Looks like a cool project.

**Comment by bo51** [comment]
Hey erickok,
i would be very happy if you would integrate jackett :)

**Comment by vicelversa** [comment]
Would also love to see jackett support!

**Comment by bo51** [comment]
Still interested :)
Thank you

**Comment by erickok** [comment]
I am working on this, though no promises.

**Comment by erickok** [comment]
So I set up a basic Jacket server and read the docs, but Jacket simply offers RSS feeds too. WOuldn't it be enoughto make it posible to add custom RSS search urls to the app? Then you cover Jacket as well as any other site the offers RSS feeds as search API (which is somewhat often, including some private sites).

Jacket doesn't seem to provide an API anyway to get the list of installed services/sites so the API wouldn't be much more fluent in that respect either.

**Comment by lozbrown** [comment]
Some of the other projects have implemented this via the torznab protocol, and largely the gist is you do a search and the results are returned from all of indexers you have installed in Jackett.  
Do you think that's possible with RSS? I can't see anything in the manual search window. Although I can see how RSS would allow you to keep up with the things you are already tracking in Jackett

In general these sites don't have the ability to choose a specific indexer and I think that has been raised as an issue in the Jackett github but i can't find it now

The advantage here is that the indexers are maintained by a much larger community

**Comment by binhex** [comment]
@erickok im one of the people VERY keen to see this change, to me your proposal of enhancing to allow a custom feed sounds fine, as long as you can pass in the search parameter to the feed then i think it should work ok, in short it sounds good to me and maybe not as much work as you first anticipated either :-)

**Comment by erickok** [comment]
Can anyone using Jackett let me know if the new release works for them? Just add the 'RSS feed' from Jackett as 'Custom RSS site' and make sure to append `%s`. Thanks for any positive and negative feedback.

**Comment by lozbrown** [comment]
Seems to work for me so far, quite long winded to copy the URL's but thats ok!

Thanks very much

**Comment by bubufofo** [comment]
it shows random results for me not the thing i search for
