### ISSUE TITLE
HTTPS certificate expired

### ISSUE THREAD

**Issue by olejon** [erickok/transdroid-search#65]
For example going to transdroid.org > Menu > Setup guides goes to this URL: https://www.transdroid.org/download/

The HTTPS certificate expired 10 September 2017. Browsers reports the site as insecure because of this. You should renew it or temporarily use just HTTP,  or if you can't afford to renew just use HTTP. I don't see a critical reason to use HTTPS on those sites. The APKs, linked to from that page, are on GitHub which is of course secure. If you want HTTPS I can give you a link to where you can buy a certificate for 3 years for just 7 USD a year.

Transdroid is awesome and I've donated, I think various times.

Regards,
olejonbj

**Comment by erickok** [comment]
Fixed! thanks for the heads up... the certificate bot renewed it, but my server config was pointing to the old (expired) certificate. BTW I am using Letsencrypt which is free and very easy and awesome.

**Comment by olejon** [comment]
Thanks for the tip! I've been following them and their initiative. Last I checked I don't think they had gotten to the point of becoming a CA. Now my main host in Norway offers free HTTPS for all customers without any extra cost so going for that there. On my personal servers I'm going to check Letsencrypt vs my current which is Comodo (their pretty huge), 99,98 % compatibility or something :P, but gives warning in some older version of Android (AOSP/Emulator), it's likely that the OEM at least has at least issued an update for that, if they use the stock WebView at all. Maybe they use some custom which they can update the trusted certificates db in the background. So for my apps with still a considerable user base on Android Jelly Bean, I have to check.

**Comment by olejon** [comment]
And BTW make sure to check your bot for future use, since your awesome app requires manuslly downloading APKs and enabling Unknown Sources for APKs potential users might be frightened facing an expired HTTPS certificate which they have to just trust to get to the page. You may lose users and hence donations, which you don't deserve. You deserve donations :)

How stupid of Google and Apple not allowing BitTorrent clients, even just Torrent client remote controls like yours! Plenty of websites distribute large files through torrents today, not just Linux distro, some even making it the default download method.

I'm using rTorrent on a Linux KVM virtual server solely for rTorrent. It's connected through OpenVPN to one of AirVPN's servers (a community of tech enthusiasts with great support and features, not for big profit). Since they allow opening ports from the external VPN server's IP to your local client (using LAN IP range) very easily through their web interface, I can easily open the port to rTorrent's RPC to access it with Transdroid through the VPN's external IP, which I have set as a DNS pointer for my domain to not have to remember the IP. The firewall on the virtual server only allows connecting to one IP +port through the Ethernet interface, namely the VPN server's access IP which is different from the external IP it uses facing the Internet. After successfully connected the firewall rejects all outgoing packets not going through the VPN tunnel virtual interface, and rejects all incoming packets except my LAN and the RPC port and the port I have opened for rTorrent to use true P2P. After the VPN and firewall is up it launches rTorrent bound to the VPN virtual interface, so if the connection drops, no package can leak, also my OpenVPN client is configured to kill rTorrent if connection drops and block all traffic except incoming from LAN (SSH port only). If connection is re-established automatically the process starts again with the firewall accepting again incoming connections on RPC and the torrent port through the VPN virtual interface.

OpenVPN FTW. So customizable and works on all desktop and mobile devices.

Just some technical details you might find interesting. I'm also a Android dev with all code on GitHub, free and no ads, just use Firebase for analytics (the new Google service for analytics replacing the horrible Google Analytics which is really for web). You may want to check it out if not using it to see more about your user base. But I'm afraid it might only work (give you the JSON file necessary to put in your project) if on the Google Play Store. But after that it should report from users having installed from other app stores as well, so maybe you can link it to your Transdrone app and in Firebase console just add the fingerprints of Transdroid then download the JSON file.
