### ISSUE TITLE
[Refactoring Suggestion] - Group Adapters Together

### ISSUE THREAD

**Issue by alonalbert** [erickok/transdroid-search#69]
I'd like to propose a new package strucure for adapters.
Instead of:
org.transdroid.search
  Site1
  Site2
  SomeMoreSites...
  gui
  RssFeedSearch
  Site10
  Site11
  SomeMoreSites...

Where each Site package has a single file, I propose:
org.transdroid.search
  adapters
    public
    private
    rss
      public
      private
  gui

This will group similar adapters together and make it easier to anage.

I'll be happy to create a PR.

**Comment by erickok** [comment]
Yes we can restructure. PR very welcome! (Make sure to merge master into dev.) Perhaps put 'rss' inside of 'public' though, as all of those are public sites.
