### ISSUE TITLE
Latest two releases won't update

### ISSUE THREAD

**Issue by dima-ser** [erickok/transdroid-search#75]
When trying to update to 3.9 or 3.10 from previous version, getting an error "App not installed".

Uninstalling the previous version and installing the latest version from scratch works.

**Comment by erickok** [comment]
The 3.9 release didn't have the proper certificate. But that was fixed with
the 3.10 release, so all is good.

**Comment by lozbrown** [comment]
I had this problem with 3.10 too, or should it be solved from now on?

**Comment by erickok** [comment]
You had this problem because you had 3.9 installed. Indeed there shouldn't
be any more issues from now on. A next update (if I don't mess up again)
will be installable normally, without uninstalling first.
