### ISSUE TITLE
v.10 stalls ttorrent client and source list

### ISSUE THREAD

**Issue by fallendaemon** [erickok/transdroid-search#76]
v.10 crashes ttorrent client when choosing a torrent the app. Also there are no more torrent site sources to choose from, IE, no drop down list or site name.
UPDATE: Deleted v.10 torrent search and downloaded and installed manually and reran ttorrent pro and now working fine. Seems that when the TTorrent app updates the search engine it doesn't work.

**Comment by erickok** [comment]
What about from Transdroid? Nothing really changed in the public API of this library, only the supported providers.

Note that the 3.9 release was signed with a wrong certificate, so you should really not use that.
