### ISSUE TITLE
RARBG Search doesnt work

### ISSUE THREAD

**Issue by 123chuck123** [erickok/transdroid-search#78]
When I type something into the searchbar using RARBG nothing happens.
No results appear.
The circle just turns for a split second.
I have been having this issue for about a week now.
Using latest version of Transdroid and Transdroid Search.
Could you fix this please.
Thank you.

**Comment by erickok** [comment]
Thanks @lightglitch !

**Comment by lightglitch** [comment]
@erickok can you make release?

**Comment by chewy74** [comment]
It looks like sky torrent search is also not working @erickok

**Comment by erickok** [comment]
I'll try to work on it soon after my holiday.

**Comment by chewy74** [comment]
Now limetorrent search is down also

**Comment by erickok** [comment]
Fixed.
