### ISSUE TITLE
Can't leave / save settings

### ISSUE THREAD

**Issue by KopCed** [erickok/transdroid-search#81]
Have installed the apk, but when start the app an list with public and private sites are shown. But how to save and leave settings ? Running Android 8.0 on OnePlus 5

**Comment by erickok** [comment]
Settings are saved as you go. Just enable/disable sites and fill in any
credentials for private sites.

**Comment by KopCed** [comment]
But when I start the app next time the list of the sites are back. And I can't make any searches. So the question should be. How to search :-) I have used the app before (before I reinstalled the the phone).

So after install Torrent Search app. I start the app. An list of all sites. Then I press back the phone. The app close. But when start the app next time, the same list of sits shows. So I can't figure out how to start search.

**Comment by KopCed** [comment]
I have solved my problem. The search are made in the torrent app :-) I have downloaded Transdroid app from the Play store. That version seems not have the search function.

**Comment by erickok** [comment]
True you need Transdroid from my site, not the Transdrone lite version available in the Play Store.

**Comment by KopCed** [comment]
Yes. Took me some hours tog figure that out. 😂😂

Den tis 3 apr. 2018 09:01Eric Kok <notifications@github.com> skrev:
