### ISSUE TITLE
Scambio etico problem

### ISSUE THREAD

**Issue by Snake87r** [erickok/transdroid-search#83]
Hello,
ther's a problem with the scambio etico search engine,
If i made a research in the program there are 21 result, but if i made the research in the site there are more result (every page of the site have 21 result, the program show only the first page)
This is the link of the site (Probably they use HTTP POST method):
http://www.tntvillage.scambioetico.org/?releaselist

Here you can see with the search world "Topolino" the result:
![sketch-1523352327184](https://user-images.githubusercontent.com/11518907/38548408-0093ee90-3cb2-11e8-85fb-51228722dc1d.png)

**Comment by erickok** [comment]
Yes this is by design, I only query the first results page.
