### ISSUE TITLE
Scambio etico doesn't work

### ISSUE THREAD

**Issue by Snake87r** [erickok/transdroid-search#84]
Hello, if i search with scambio etico plugin and then clickcon a result i can't download the file:
![sketch-1523354594465](https://user-images.githubusercontent.com/11518907/38550587-352cd180-3cb7-11e8-9a60-0145a426a422.png)
![sketch-1523354597673](https://user-images.githubusercontent.com/11518907/38550597-3ba98a12-3cb7-11e8-83c5-37938bfd2d69.png)
![sketch-1523354807336](https://user-images.githubusercontent.com/11518907/38550769-ab1263b0-3cb7-11e8-8680-5d9c90668f13.png)

**Comment by erickok** [comment]
Just use the + button. The link button is to open the website.

**Comment by Snake87r** [comment]
Ok, tested and doesn't work, the program say torrent added but the torrent isn't added.
If i copy the link (torrent or magnet directly from the site) and add manually throught web interface on my raspberry trasmission server work correctly.

So i added to transdroid a scambioetico rss feed and with this method work correctly:
http://www.tntvillage.scambioetico.org/rss.php?c=2

**Comment by erickok** [comment]
Site seems totally offline now. :( (cf https://www.hwupgrade.it/news/web/tntvillage-a-rischio-chiusura-il-sito-per-lo-scambio-etico-via-link-torrent_77861.html)
