### ISSUE TITLE
No search engines with Transdroid-search > 3.8

### ISSUE THREAD

**Issue by storm49152** [erickok/transdroid-search#85]
If I uninstall Transdroid-search 3.8 and then install 3.9 or 3.10 (or simply update, doesn't matter), I cannot search torrents anymore. When checking settings, there are no search engines listed. Reverting to 3.8 fixes this. I'm on Transdroid 2.5.10.

Since the app (of course) keeps saying 3.10 is available, how can I fix this?

**Comment by erickok** [comment]
3.10 should work... (3.9 had an issue with the signing so you can't install this version 'over' a 3.9, not can you install 3.10 'over' 3.9...)

**Comment by storm49152** [comment]
I have no doubt it should work; otherwise I think someone else would have reported this already. ;-)

Like I wrote: I uninstalled the installed Transdroid-search before installing 3.10. I repeated this several times for each version, but keep getting the same result. Version 3.8 works for me, 3.10 does not and Transdroid does not show any torrent sites that can be searched.

Is there any way I can troubleshoot this? Are there any cache or configuration files that I can remove to start fresh?

**Comment by erickok** [comment]
Probably you are experiencing https://github.com/erickok/transdroid/issues/417

**Comment by storm49152** [comment]
Just tried that. Uninstalled both Transdroid and Search. Installed 2.5.12 with 3.10. Disabled battery optimization for both, just to be sure. Had to add the Transmission server because settings were lost (not an issue for me). Checked the search engine list in settings, and it's empty. FTR, I'm currently on OP5 with LineageOS-15.1-20181008.
