### ISSUE TITLE
No results from RARBG in UK. Not a proxy issue.

### ISSUE THREAD

**Issue by diem1000000** [erickok/transdroid-search#86]
Hi.

I can no longer get results from RARBG using Torrent Search in Transdroid. Other providers such as the pirate bay work fine but RARBG always comes back with no results. I don't think this is a proxy issue (RARBG is blocked in the UK) as I use TunnelBear to spoof my phone location and have tried multiple countries. Plus I think it used to work even while RARBG was blocked for a while.

Any ideas? 

Thanks.

**Comment by diem1000000** [comment]
It's worth noting that I'm on both the latest version of Transdroid and Transdroid search (both clean installs) so the api change from issue 78/79 should be in effect but still no luck.

Thanks.

**Comment by erickok** [comment]
Yes sorry I forgot to release. Fixed by #79.
