### ISSUE TITLE
torrentdownloads, choosing search results fails

### ISSUE THREAD

**Issue by jobe451** [erickok/transdroid-search#87]
1. I enter some search term
2. I search for it in "torrent downloads"
3. Some results appear
4. I choose/tap a result
5. The main view of transdroid appears, I see the standard "spinner" for a short moment, but nothing happens

=> this happens for anythings I choose always. Nothing results in an actual download since about 2 month

When I search directly on https://www.torrentdownloads.me/ the magnetic links there work just fine.

**Comment by peterjanes** [comment]
This appears to have resurfaced; if I use the web interface I get a Cloudflare "checking your browser, wait up to five seconds" page that never goes any further. (Magnet links are fine.)
