### ISSUE TITLE
Could you add EZTV support please 

### ISSUE THREAD

**Issue by Mongoose69** [erickok/transdroid-search#90]

**Comment by erickok** [comment]
While there is an API (https://eztv.ag/api/) it seems only to return recent torrents, not searchable. There's a lookup by IMDB id, but no free text search. Screen scraping seems an option though.

**Comment by Mongoose69** [comment]
There's a search plugin on Synology DSM, also another app searches it but without options for sorting etc

**Comment by Mongoose69** [comment]
@erickok There's a search plugin on Synology DSM, also another app searches it but without options for sorting etc

**Comment by erickok** [comment]
Sure, they probably also scrape.

**Comment by robinpaulson** [comment]
qbittorrent provide this plugin to search eztv. it appears to scrape, and is written in python. i'm sure it's portable to java, etc. though

https://github.com/qbittorrent/search-plugins/blob/master/nova3/engines/eztv.py

as are all the other qb plugins:
https://github.com/qbittorrent/search-plugins/blob/master/nova3/engines/
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
