### ISSUE TITLE
F-Droid cannot build newer versions due to blob

### ISSUE THREAD

**Issue by IzzySoft** [erickok/transdroid-search#91]
Starting with ~v3.8, your app includes a "blob" (here: a JAR binary in `app/libs/`). As F-Droid only builds apps *completely* from source, this is a show-stopper (see [here](https://gitlab.com/fdroid/fdroiddata/issues/1007) for reference).

Instead of directly including this: could you pull it from a trusted Maven repo, or include its code via a git submodule – so F-Droid can update your app again?

**Comment by erickok** [comment]
Wow this has been in the app since forever... 

Okay will look into it. Should be easy... I hope.

**Comment by IzzySoft** [comment]
That would be great – thanks in advance!

**Comment by IzzySoft** [comment]
@erickok Any news?

**Comment by IzzySoft** [comment]
Thanks!
